twig:
    file_name_pattern: '*.twig'
    form_themes: ['form/dsfr.html.twig']
    paths:
          '%kernel.project_dir%/assets/images': images


when@test:
    twig:
        strict_variables: true

